### ISSUE TITLE
Dependency hampe/inky is abandoned

### ISSUE THREAD

**Issue by LeonidasJP** [Prezent/prezent-ink-bundle#1]
De bundle `hampe/inky` is abandoned, versie `1.3.6.2` van 30 augustus 2016 is de laatste release.

Nieuwe HTML-parser schrijven om de werking van `hampe/inky` over te nemen?

**Comment by sandermarechal** [comment]
I have released prezent/ink-bundle 0.3 with replaces hanmpe/inky with a brand new (and faster) inky parser. Please test it well!
