### ISSUE TITLE
PrezentInkBundle cannot generate HTML with Libxml 2.7.6-backend

### ISSUE THREAD

**Issue by LeonidasJP** [Prezent/prezent-ink-bundle#4]
Prezent/Inky is unable to generate HTML if LibXML 2.7.7 or earlier is being used, due to the lack of `LIBXML_HTML_NOIMPLIED` and `LIBXML_HTML_NODEFDTD` constants in PHP.

Some hosting providers are still running on CentOS 6, which ships with LibXML 2.7.6 as the latest available update, thus generating empty HTML Mail bodies.

Is it possible to fallback to generating Text-Only mails when LibXML is too old to generate HTML? That way, recipients will at least recieve some kind of mail body, instead of an empty E-mail...

**Comment by sandermarechal** [comment]
The entire point of this bundle is generating HTML emails, so I am not going to send out text-only versions.

I have taken a look at the CentOS 6 situation. CentOS 6 ships with PHP 5.3.3 which is too old for this bundle anyway (it requires PHP 5.5+). Any newer PHP builds for CentOS 6 (like the Remi repository) are just personal repositories or custom builds. They should be built against the correct libxml version.
I have added a restriction in composer.json to require at least libxml 2.7.8.
